---
title: "COVID-19 DataFest"
author: "Nagaprasad Rudrapatna and Jackson Muraika"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(stringr)
library(knitr)
library(tidyverse)
library(gridExtra)
library(leaps)
library(rms)
```

```{r load-data, message = FALSE}
whirlpool <- read_csv("data/whirlpool.csv")
lewiston_queenston <- read_csv("data/lewistonQueenston.csv")
rainbow <- read_csv("data/rainbow.csv")
bridges_total <- read_csv("data/combined_bridges.csv")

whirlpool <- whirlpool %>%
  select(Date, Day, `US Bound`)

lewiston_queenston <- lewiston_queenston %>%
  select(Date, Day, `US Bound`)

rainbow <- rainbow %>%
  select(Date, Day, `US Bound`)

bridges_total <- bridges_total %>%
  select(Date, Day, Auto, Bus, Truck, `RV/Limo`, `US Bound`)

glimpse(whirlpool)
glimpse(rainbow)
glimpse(lewiston_queenston)
glimpse(bridges_total)
```

```{r join}

```

### Research Question and Objective

How has COVID-19 impacted unemployment claims?


### The Data 

`https://oui.doleta.gov/unemploy/archive.asp`

Feb 1
Feb 8
Feb 15
Feb 22
Feb 29
March 7
March 14
March 21
March 28
April 4

Join by week

State population level

### Exploratory Data Analysis


### Modeling Approach


### Final Model and Brief Discussion of Assumptions


### Interpretations and Significance


